import * as z from 'zod';

export const petDetailsSchema = z.object({
  internalId: z.string().optional().nullable(),
  name: z.string().optional().nullable(),
  spieces: z.string().optional().nullable(),
  breed: z.string().optional().nullable(),
  gender: z.string().optional().nullable(),
  age: z.string().optional().nullable(),
  color: z.string().optional().nullable(),
  coat: z.string().optional().nullable(),
  weight: z.number().optional().nullable(),
  adoptionFee: z.number().optional().nullable(),
  dateOfBirth: z.string().optional().nullable(),
  status: z.string().optional().nullable(),
  description: z.string().optional().nullable(),
  houseTrained: z.boolean().optional().nullable(),
  specialNeeds: z.boolean().optional().nullable(),
  neutered: z.boolean().optional().nullable(),
  declawed: z.boolean().optional().nullable(),
  aggressive: z.boolean().optional().nullable(),
  friendlyWithDogs: z.boolean().optional().nullable(),
  friendlyWithCats: z.boolean().optional().nullable(),
  friendlyWithChildren: z.boolean().optional().nullable(),
  microchipBrand: z.string().optional().nullable(),
  microchipNumber: z.string().optional().nullable(),
  shelter: z.object({}),
  shelterId: z.string(),
  healthStatus: z.union([
    z.literal('HEALTHY'),
    z.literal('INJURED'),
    z.literal('SICK'),
    z.literal('TREATED'),
    z.literal('QUARANTINE'),
    z.literal('DEAD'),
  ]),
  medicalEvents: z.array(z.object({})),
  intakeEvent: z.object({}).optional().nullable(),
  outcomeEvents: z.array(z.object({})),
  photos: z.array(z.object({})),
  documents: z.array(z.object({})),
  createdAt: z.date(),
  updatedAt: z.date(),
});

export type IPetDetails = z.infer<typeof petDetailsSchema>;
