export const links = {
  home: '/',
  welcome: '/welcome',
  dashboard: '/dashboard',
  animals: '/animals',
  users: '/users',
  userSettings: '/user/settings',
  favorites: '/user/favorites',
  featured: '#featured',
  scrollToPosition: '#scrollToPosition',
  results: (type: string) => `/${type}#scrollToPosition`,
  resultsPosition: '/pets#scrollToPosition',
  search: (type: string, query: string) =>
    `/${type}?search=${query}#scrollToPosition`,
  searchDogs: '/pets?search=pies#scrollToPosition',
  searchCats: '/pets?search=kot#scrollToPosition',
  about: '/about',
  adoption: '/adoption',
  contact: '/contact',
  signInAPI: '/api/auth/signin',
  phone: (phoneNumber: string) => `tel:${phoneNumber}`,
  email: (email: string) => `mailto:${email}`,
  organizations: '/organizations',
  organizationSettings: '/organization/settings',
  organization: (organizationId: string) => `/organization/${organizationId}`,
  organizationPets: (organizationId: string) =>
    `/organization/${organizationId}/pets`,
  animal: (animalId: string) => `/animal/${animalId}`,
  person: (personId: string) => `/user/${personId}`,
  registerAnimal: '/animal/register',
  registerUser: '/user/register',
  donations: '/donations',
  donate: (petId: string) => `/donate/${petId}`,
  user: (userId: string) => `/user/${userId}`,
  redirectTo: (variant: string, id: string) => `${variant}/${id}`,
  termsOfService: '/termsOfService',
  privacyPolicy: '/privacyPolicy',
  facebook: '/tba',
};
