export const links = {
  home: '/',
  welcome: '/welcome',
  dashboard: '/dashboard',
  animals: '/animals',
  users: '/users',
  userSettings: '/user/settings',
  favorites: '/user/favorites',
  featured: '#featured',
  globalStatistics: '#globalStatistics',
  searchByBreed: '#searchByBreed',
  searchByState: '#searchByState',
  footer: '#footer',
  scrollToPosition: '#scrollToPosition',
  results: (type: string) => `/${type}`,
  search: (type: string, query: string) => `/${type}?search=${query}`,
  searchDogs: '/pets?search=pies',
  searchCats: '/pets?search=kot',
  about: '/about',
  adoption: '/adoption',
  contact: '/about#contact',
  signInAPI: '/api/auth/signin',
  phone: (phoneNumber: string) => `tel:${phoneNumber}`,
  email: (email: string) => `mailto:${email}`,
  organizations: '/organizations',
  organizationSettings: '/organization/settings',
  organization: (organizationId: string) => `/organization/${organizationId}`,
  organizationPets: (organizationId: string) =>
    `/organization/${organizationId}/pets`,
  pet: (petId: string) => `/pet/${petId}`,
  animal: (animalId: string) => `/animal/${animalId}`,
  person: (personId: string) => `/user/${personId}`,
  registerAnimal: '/animal/register',
  registerUser: '/user/register',
  donations: '/donations',
  donate: (petId: string) => `/donate/${petId}`,
  user: (userId: string) => `/user/${userId}`,
  redirectTo: (variant: string, id: string) => `/${variant}/${id}`,
  termsOfService: '/terms-of-service',
  privacyPolicy: '/privacy-policy',
  facebook: '/about#facebook',
  findYourPet: '/find-your-pet',
  signIn: '/signin',
  checkInbox: '/check-inbox',
  checkInboxForInviteDecision: '/check-inbox?joinRequest=shelter',
  associateShelter: '/shelter/associate',
  registerShelter: '/shelter/register',
  joinRequests: '/join-requests',
  raports: '/raports',
  adoptions: '/adoptions',
  adoptionSurvey: '/adoption-survey',
  confirmation: '/tba',
  application: (applicationId: string) =>
    `/adoption-application/${applicationId}`,
};
