export const dogBreeds = [
  {
    en: 'Cocker Spaniel',
    pl: 'Cocker Spaniel',
  },
  { en: 'Labrador Retriever', pl: 'Labrador' },
  { en: 'German Shepherd Dog', pl: 'Owczarek Niemiecki' },
  { en: 'Golden Retriever', pl: 'Golden Retriever' },
  { en: 'French Bulldog', pl: 'Buldog francuski' },
  { en: 'Poodle', pl: 'Pudel' },
  { en: 'Beagle', pl: 'Beagle' },
  { en: 'Dachshund', pl: 'Jamnik' },
  { en: 'Rottweiler', pl: 'Rottweiler' },
  { en: 'Yorkshire Terrier', pl: 'York' },
  { en: 'Corgi', pl: 'Corgi' },
  { en: 'Akita', pl: 'Akita' },
  { en: 'Affenpinscher', pl: 'Affenpinscher' },
  { en: 'Afghan Hound', pl: 'Afgański pies gończy' },
  { en: 'Airedale Terrier', pl: 'Terrier airedale' },
  { en: 'Alaskan Malamute', pl: 'Alaskan Malamute' },
  { en: 'American Bulldog', pl: 'Amerykański buldog' },
  {
    en: 'American English Coonhound',
    pl: 'Amerykański angielski coonhound',
  },
  {
    en: 'American Eskimo Dog',
    pl: 'Amerykański eskimoski pies',
  },
  { en: 'American Foxhound', pl: 'Amerykański foxhound' },
  {
    en: 'American Pit Bull Terrier',
    pl: 'Amerykański pit bull terrier',
  },
  {
    en: 'American Staffordshire Terrier',
    pl: 'Amerykański terrier staffordshire',
  },
  {
    en: 'American Water Spaniel',
    pl: 'Amerykański spaniel wodny',
  },
  {
    en: 'Anatolian Shepherd Dog',
    pl: 'Anatolian pasterz pies',
  },
  {
    en: 'Appenzeller Sennenhund',
    pl: 'Appenzeller Sennenhund',
  },
  {
    en: 'Australian Cattle Dog',
    pl: 'Australijski pies pasterski',
  },
  { en: 'Australian Kelpie', pl: 'Australijski kelpie' },
  {
    en: 'Australian Shepherd',
    pl: 'Australijski pies pasterski',
  },
  { en: 'Australian Terrier', pl: 'Australijski terrier' },
  { en: 'Azawakh', pl: 'Azawakh' },
  { en: 'Barbet', pl: 'Barbet' },
  { en: 'Basenji', pl: 'Basenji' },
  { en: 'Basset Hound', pl: 'Basset Hound' },
  { en: 'Bearded Collie', pl: 'Owczarek szkocki' },
  { en: 'Bedlington Terrier', pl: 'Bedlington terrier' },
  {
    en: 'Belgian Malinois',
    pl: 'Belgijski owczarek malinois',
  },
  { en: 'Belgian Sheepdog', pl: 'Belgijski owczarek' },
  { en: 'Belgian Tervuren', pl: 'Belgijski owczarek' },
  { en: 'Bernese Mountain Dog', pl: 'Bernardyn' },
  { en: 'Bichon Frise', pl: 'Bichon Frise' },
  {
    en: 'Black and Tan Coonhound',
    pl: 'Black and Tan Coonhound',
  },
  {
    en: 'Black Russian Terrier',
    pl: 'Czarny terier rosyjski',
  },
  { en: 'Bloodhound', pl: 'Owczarek krwi' },
  { en: 'Bluetick Coonhound', pl: 'Bluetick Coonhound' },
  { en: 'Border Collie', pl: 'Border collie' },
  { en: 'Border Terrier', pl: 'Border terrier' },
  { en: 'Borzoi', pl: 'Borzoi' },
  { en: 'Boston Terrier', pl: 'Boston terrier' },
  { en: 'Bouvier des Flandres', pl: 'Bouvier des Flandres' },
  { en: 'Boxer', pl: 'Bokser' },
  { en: 'Boykin Spaniel', pl: 'Boykin Spaniel' },
  { en: 'Bracco Italiano', pl: 'Bracco Italiano' },
  { en: 'Briard', pl: 'Briard' },
  { en: 'Brittany', pl: 'Bretoński spaniel' },
  { en: 'Brussels Griffon', pl: 'Brabancon' },
  { en: 'Bull Terrier', pl: 'Bull terrier' },
  { en: 'Bulldog', pl: 'Buldog' },
  { en: 'Bullmastiff', pl: 'Bullmastiff' },
  { en: 'Cairn Terrier', pl: 'Cairn terrier' },
  { en: 'Canaan Dog', pl: 'Pies kananejski' },
  { en: 'Cane Corso', pl: 'Cane Corso' },
  { en: 'Catahoula Leopard Dog', pl: 'Catahoula Leopard Dog' },
  { en: 'Caucasian Shepherd Dog', pl: 'Kaukaski owczarek' },
  {
    en: 'Cavalier King Charles Spaniel',
    pl: 'Cavalier King Charles Spaniel',
  },
  {
    en: 'Central Asian Shepherd Dog',
    pl: 'Central Asian Shepherd Dog',
  },
  { en: 'Cesky Terrier', pl: 'Cesky Terrier' },
  {
    en: 'Chesapeake Bay Retriever',
    pl: 'Chesapeake Bay Retriever',
  },
  { en: 'Chihuahua', pl: 'Chihuahua' },
  { en: 'Chinese Crested', pl: 'Chiński grzywacz' },
  { en: 'Chinese Shar-Pei', pl: 'Chinese Shar-Pei' },
  { en: 'Chinook', pl: 'Chinook' },
  { en: 'Chow Chow', pl: 'Chow Chow' },
  { en: 'Clumber Spaniel', pl: 'Clumber Spaniel' },
  { en: 'Cockapoo', pl: 'Cockapoo' },
  { en: 'Collie', pl: 'Collie' },
  { en: 'Coton de Tulear', pl: 'Coton de Tulear' },
  {
    en: 'Curly-Coated Retriever',
    pl: 'Curly-Coated Retriever',
  },
  { en: 'Dalmatian', pl: 'Dalmatyńczyk' },
  {
    en: 'Dandie Dinmont Terrier',
    pl: 'Dandie Dinmont Terrier',
  },
  { en: 'Doberman Pinscher', pl: 'Doberman' },
  { en: 'Dogo Argentino', pl: 'Dogo Argentino' },
  { en: 'Dogue de Bordeaux', pl: 'Dogue de Bordeaux' },
  { en: 'Dutch Shepherd', pl: 'Dutch Shepherd' },
  { en: 'English Bulldog', pl: 'Angielski buldog' },
  { en: 'English Foxhound', pl: 'Angielski foxhound' },
  { en: 'English Setter', pl: 'Angielski Setter' },
  {
    en: 'English Springer Spaniel',
    pl: 'Angielski Springer Spaniel',
  },
  { en: 'English Toy Spaniel', pl: 'Angielski Toy Spaniel' },
  {
    en: 'Entlebucher Mountain Dog',
    pl: 'Entlebucher Mountain Dog',
  },
  { en: 'Estrela Mountain Dog', pl: 'Estrela Mountain Dog' },
  { en: 'Eurasier', pl: 'Eurasier' },
  { en: 'Field Spaniel', pl: 'Field Spaniel' },
  { en: 'Finnish Lapphund', pl: 'Finnish Lapphund' },
  { en: 'Finnish Spitz', pl: 'Finnish Spitz' },
  { en: 'Flat-Coated Retriever', pl: 'Flat-Coated Retriever' },
  { en: 'German Pinscher', pl: 'German Pinscher' },
  {
    en: 'German Shorthaired Pointer',
    pl: 'Niemiecki krótkowłosy pointer',
  },
  {
    en: 'German Wirehaired Pointer',
    pl: 'Niemiecki krótkowłosy pointer',
  },
  { en: 'Giant Schnauzer', pl: 'Giant Schnauzer' },
  { en: 'Glen of Imaal Terrier', pl: 'Glen of Imaal Terrier' },
  { en: 'Goldador', pl: 'Goldador' },
  { en: 'Goldendoodle', pl: 'Goldendoodle' },
  { en: 'Gordon Setter', pl: 'Gordon Setter' },
  { en: 'Great Dane', pl: 'Dog niemiecki' },
  { en: 'Great Pyrenees', pl: 'Great Pyrenees' },
  {
    en: 'Greater Swiss Mountain Dog',
    pl: 'Greater Swiss Mountain Dog',
  },
  { en: 'Greyhound', pl: 'Greyhound' },
  { en: 'Hamiltonstovare', pl: 'Hamiltonstovare' },
  { en: 'Havanese', pl: 'Hawańczyk' },
  { en: 'Hokkaido', pl: 'Hokkaido' },
  { en: 'Hovawart', pl: 'Hovawart' },
  { en: 'Ibizan Hound', pl: 'Ibizan Hound' },
  { en: 'Icelandic Sheepdog', pl: 'Icelandic Sheepdog' },
  {
    en: 'Irish Red and White Setter',
    pl: 'Irish Red and White Setter',
  },
  { en: 'Irish Setter', pl: 'Irish Setter' },
  { en: 'Irish Terrier', pl: 'Irish Terrier' },
  { en: 'Irish Water Spaniel', pl: 'Irish Water Spaniel' },
  { en: 'Irish Wolfhound', pl: 'Irish Wolfhound' },
  { en: 'Italian Greyhound', pl: 'Italian Greyhound' },
  { en: 'Jack Russell Terrier', pl: 'Jack Russell Terrier' },
  { en: 'Japanese Chin', pl: 'Japanese Chin' },
  { en: 'Japanese Spitz', pl: 'Japanese Spitz' },
  { en: 'Japanese Terrier', pl: 'Japanese Terrier' },
  { en: 'Jindo', pl: 'Jindo' },
  { en: 'Kai Ken', pl: 'Kai Ken' },
  { en: 'Karelian Bear Dog', pl: 'Karelian Bear Dog' },
  { en: 'Keeshond', pl: 'Keeshond' },
  { en: 'Kerry Blue Terrier', pl: 'Kerry Blue Terrier' },
  { en: 'Kishu Ken', pl: 'Kishu Ken' },
  { en: 'Komondor', pl: 'Komondor' },
  { en: 'Kooikerhondje', pl: 'Kooikerhondje' },
  { en: 'Korean Jindo Dog', pl: 'Korean Jindo Dog' },
  { en: 'Kromfohrlander', pl: 'Kromfohrlander' },
  { en: 'Kuvasz', pl: 'Kuvasz' },
  { en: 'Labradoodle', pl: 'Labradoodle' },
  { en: 'Lagotto Romagnolo', pl: 'Lagotto Romagnolo' },
  { en: 'Lakeland Terrier', pl: 'Lakeland Terrier' },
  { en: 'Lancashire Heeler', pl: 'Lancashire Heeler' },
  { en: 'Leonberger', pl: 'Leonberger' },
  { en: 'Lhasa Apso', pl: 'Lhasa Apso' },
  { en: 'Lowchen', pl: 'Lowchen' },
  { en: 'Maltese', pl: 'Maltańczyk' },
  { en: 'Manchester Terrier', pl: 'Manchester Terrier' },
  { en: 'Maremma Sheepdog', pl: 'Maremma Sheepdog' },
  { en: 'Mastiff', pl: 'Mastiff' },
  {
    en: 'Miniature American Shepherd',
    pl: 'Miniature American Shepherd',
  },
  {
    en: 'Miniature Bull Terrier',
    pl: 'Miniature Bull Terrier',
  },
  { en: 'Miniature Pinscher', pl: 'Miniature Pinscher' },
  { en: 'Miniature Schnauzer', pl: 'Miniature Schnauzer' },
  { en: 'Mountain Cur', pl: 'Mountain Cur' },
  { en: 'Mudi', pl: 'Mudi' },
  { en: 'Neapolitan Mastiff', pl: 'Neapolitan Mastiff' },
  { en: 'Newfoundland', pl: 'Newfoundland' },
  { en: 'Norfolk Terrier', pl: 'Norfolk Terrier' },
  { en: 'Norwegian Buhund', pl: 'Norwegian Buhund' },
  { en: 'Norwegian Elkhound', pl: 'Norwegian Elkhound' },
  { en: 'Norwegian Lundehund', pl: 'Norwegian Lundehund' },
  { en: 'Norwich Terrier', pl: 'Norwich Terrier' },
  { en: 'Old English Sheepdog', pl: 'Old English Sheepdog' },
  { en: 'Otterhound', pl: 'Otterhound' },
  { en: 'Papillon', pl: 'Papillon' },
  {
    en: 'Parson Russell Terrier',
    pl: 'Parson Russell Terrier',
  },
  { en: 'Pekingese', pl: 'Pekingese' },
  {
    en: 'Peruvian Inca Orchid',
    pl: 'Peruwiański pies bezwłosy',
  },
  {
    en: 'Petit Basset Griffon Vendeen',
    pl: 'Petit Basset Griffon Vendeen',
  },
  { en: 'Pharaoh Hound', pl: 'Owczarek faraona' },
  { en: 'Plott', pl: 'Plott' },
  { en: 'Pointer', pl: 'Pointer' },
  {
    en: 'Polish Lowland Sheepdog',
    pl: 'Polish Lowland Sheepdog',
  },
  { en: 'Pomeranian', pl: 'Pomeranian' },
  { en: 'Portuguese Podengo', pl: 'Portugalski Podengo' },
  { en: 'Portuguese Pointer', pl: 'Portugalski pointer' },
  { en: 'Portuguese Water Dog', pl: 'Portugalski pies wodny' },
  { en: 'Pudelpointer', pl: 'Pudelpointer' },
  { en: 'Pug', pl: 'Mops' },
  { en: 'Puli', pl: 'Puli' },
  { en: 'Pumi', pl: 'Pumi' },
  { en: 'Pyrenean Mastiff', pl: 'Pyrenean Mastiff' },
  { en: 'Pyrenean Shepherd', pl: 'Pyrenean Shepherd' },
  { en: 'Rafeiro do Alentejo', pl: 'Rafeiro do Alentejo' },
  { en: 'Rat Terrier', pl: 'Rat Terrier' },
  { en: 'Redbone Coonhound', pl: 'Redbone Coonhound' },
  { en: 'Rhodesian Ridgeback', pl: 'Rhodesian Ridgeback' },
  { en: 'Russell Terrier', pl: 'Russell Terrier' },
  { en: 'Russian Toy', pl: 'Rosyjski toy' },
  {
    en: 'Russian Tsvetnaya Bolonka',
    pl: 'Rosyjski Tsvetnaya Bolonka',
  },
  { en: 'Saint Bernard', pl: 'Święty Bernard' },
  { en: 'Saluki', pl: 'Saluki' },
  { en: 'Samoyed', pl: 'Samoyed' },
  { en: 'Schapendoes', pl: 'Schapendoes' },
  { en: 'Schipperke', pl: 'Schipperke' },
  { en: 'Scottish Deerhound', pl: 'Szkocki deerhound' },
  { en: 'Scottish Terrier', pl: 'Szkocki terrier' },
  { en: 'Sealyham Terrier', pl: 'Sealyham Terrier' },
  { en: 'Shetland Sheepdog', pl: 'Owczarek Shetland' },
  { en: 'Shiba Inu', pl: 'Shiba Inu' },
  { en: 'Shih Tzu', pl: 'Shih Tzu' },
  { en: 'Siberian Husky', pl: 'Syberyjski Husky' },
  { en: 'Silky Terrier', pl: 'Silky Terrier' },
  { en: 'Skye Terrier', pl: 'Skye Terrier' },
  { en: 'Sloughi', pl: 'Sloughi' },
  {
    en: 'Slovakian Wirehaired Pointer',
    pl: 'Slovakian Wirehaired Pointer',
  },
  {
    en: 'Small Munsterlander Pointer',
    pl: 'Small Munsterlander Pointer',
  },
  { en: 'Smooth Fox Terrier', pl: 'Smooth Fox Terrier' },
  {
    en: 'Soft-Coated Wheaten Terrier',
    pl: 'Soft-Coated Wheaten Terrier',
  },
  { en: 'Spanish Mastiff', pl: 'Hiszpański Mastiff' },
  { en: 'Spanish Water Dog', pl: 'Hiszpański pies wodny' },
  { en: 'Spinone Italiano', pl: 'Spinone Italiano' },
  { en: 'Stabyhoun', pl: 'Stabyhoun' },
  {
    en: 'Staffordshire Bull Terrier',
    pl: 'Staffordshire Bull Terrier',
  },
  { en: 'Standard Schnauzer', pl: 'Standard Schnauzer' },
  { en: 'Sussex Spaniel', pl: 'Sussex Spaniel' },
  { en: 'Swedish Lapphund', pl: 'Swedish Lapphund' },
  { en: 'Swedish Vallhund', pl: 'Swedish Vallhund' },
  { en: 'Taiwan Dog', pl: 'Pies tajwański' },
  {
    en: 'Teddy Roosevelt Terrier',
    pl: 'Teddy Roosevelt Terrier',
  },
  { en: 'Thai Ridgeback', pl: 'Thai Ridgeback' },
  { en: 'Tibetan Mastiff', pl: 'Tybetański Mastiff' },
  { en: 'Tibetan Spaniel', pl: 'Tybetański Spaniel' },
  { en: 'Tibetan Terrier', pl: 'Tybetański Terrier' },
  { en: 'Tornjak', pl: 'Tornjak' },
  { en: 'Tosa', pl: 'Tosa' },
  { en: 'Toy Fox Terrier', pl: 'Toy Fox Terrier' },
  { en: 'Transylvanian Hound', pl: 'Transylvanian Hound' },
  {
    en: 'Treeing Tennessee Brindle',
    pl: 'Treeing Tennessee Brindle',
  },
  {
    en: 'Treeing Walker Coonhound',
    pl: 'Treeing Walker Coonhound',
  },
  { en: 'Vizsla', pl: 'Vizsla' },
  { en: 'Weimaraner', pl: 'Weimaraner' },
  {
    en: 'Welsh Springer Spaniel',
    pl: 'Welsh Springer Spaniel',
  },
  { en: 'Welsh Terrier', pl: 'Welsh Terrier' },
  {
    en: 'West Highland White Terrier',
    pl: 'West Highland White Terrier',
  },
  { en: 'Whippet', pl: 'Whippet' },
  { en: 'Wire Fox Terrier', pl: 'Wire Fox Terrier' },
  {
    en: 'Wirehaired Pointing Griffon',
    pl: 'Wirehaired Pointing Griffon',
  },
  { en: 'Wirehaired Vizsla', pl: 'Wirehaired Vizsla' },
  { en: 'Working Kelpie', pl: 'Working Kelpie' },
  { en: 'Xoloitzcuintli', pl: 'Xoloitzcuintli' },
  { en: 'Yorkipoo', pl: 'Yorkipoo' },
];

export const catBreeds = [
  { en: 'Abyssinian', pl: 'Abyssinian' },
  { en: 'American Bobtail', pl: 'Amerykański Bobtail' },
  { en: 'American Curl', pl: 'Amerykański Curl' },
  { en: 'American Shorthair', pl: 'Amerykański krótkowłosy' },
  { en: 'American Wirehair', pl: 'Amerykański Wirehair' },
  { en: 'Applehead Siamese', pl: 'Applehead Syjamski' },
  { en: 'Balinese', pl: 'Balijski' },
  { en: 'Bengal', pl: 'Bengalski' },
  { en: 'Birman', pl: 'Birmański' },
  { en: 'Bombay', pl: 'Bombajski' },
  { en: 'British Shorthair', pl: 'Brytyjski krótkowłosy' },
  { en: 'Burmese', pl: 'Birmański' },
  { en: 'Burmilla', pl: 'Burmilla' },
  { en: 'Calico', pl: 'Calico' },
  { en: 'Canadian Hairless', pl: 'Kanadyjski bezwłosy' },
  { en: 'Chartreux', pl: 'Chartreux' },
  { en: 'Chausie', pl: 'Chausie' },
  { en: 'Chinchilla', pl: 'Chinchilla' },
  { en: 'Cornish Rex', pl: 'Cornish Rex' },
  { en: 'Cymric', pl: 'Cyryjski' },
  { en: 'Devon Rex', pl: 'Devon Rex' },
  { en: 'Dilute Calico', pl: 'Rozmyte Calico' },
  { en: 'Dilute Tortoiseshell', pl: 'Rozmyte Tortoiseshell' },
  { en: 'Domestic Long Hair', pl: 'Domowy długość włosów' },
  {
    en: 'Domestic Medium Hair',
    pl: 'Domowy średniej długości włosów',
  },
  { en: 'Domestic Short Hair', pl: 'Domowy krótkowłosy' },
  { en: 'Egyptian Mau', pl: 'Egipski Mau' },
  { en: 'Exotic Shorthair', pl: 'Egzotyczny krótkowłosy' },
  { en: 'Havana', pl: 'Hawana' },
  { en: 'Himalayan', pl: 'Himalajski' },
  { en: 'Japanese Bobtail', pl: 'Japoński Bobtail' },
  { en: 'Javanese', pl: 'Jawajski' },
  { en: 'Korat', pl: 'Korat' },
  { en: 'LaPerm', pl: 'LaPerm' },
  { en: 'Maine Coon', pl: 'Maine Coon' },
  { en: 'Manx', pl: 'Manx' },
  { en: 'Munchkin', pl: 'Munchkin' },
  { en: 'Nebelung', pl: 'Nebelung' },
  { en: 'Norwegian Forest Cat', pl: 'Norweski leśny' },
  { en: 'Ocicat', pl: 'Ocicat' },
  {
    en: 'Oriental Long Hair',
    pl: 'Orientalny długo włosy',
  },
  { en: 'Oriental Short Hair', pl: 'Orientalny krótkowłosy' },
  { en: 'Oriental Tabby', pl: 'Orientalny Tabby' },
  { en: 'Persian', pl: 'Perski' },
  { en: 'Pixiebob', pl: 'Pixiebob' },
  { en: 'Ragamuffin', pl: 'Ragamuffin' },
  { en: 'Ragdoll', pl: 'Ragdoll' },
  { en: 'Russian Blue', pl: 'Rosyjski niebieski' },
  { en: 'Scottish Fold', pl: 'Szkockie' },
  { en: 'Selkirk Rex', pl: 'Selkirk Rex' },
  { en: 'Siamese', pl: 'Syjamski' },
  { en: 'Siberian', pl: 'Syberyjski' },
  { en: 'Silver', pl: 'Srebrny' },
  { en: 'Singapura', pl: 'Singapurski' },
  { en: 'Snowshoe', pl: 'Snowshoe' },
  { en: 'Somali', pl: 'Somalijski' },
  { en: 'Sphynx', pl: 'Sfinks' },
  { en: 'Tabby', pl: 'Pręgowaty' },
  { en: 'Tiger', pl: 'Tygrys' },
  { en: 'Tonkinese', pl: 'Tonkiński' },
  { en: 'Torbie', pl: 'Torbik' },
  { en: 'Tortoiseshell', pl: 'Tortoiseshell' },
  { en: 'Toyger', pl: 'Toyger' },
  { en: 'Turkish Angora', pl: 'Turecki angora' },
  { en: 'Turkish Van', pl: 'Turecki Van' },
  { en: 'Tuxedo', pl: 'Tuxedo' },
  { en: 'York Chocolate', pl: 'York Chocolate' },
  { en: 'Unknown', pl: 'Nieznany' },
];
