name: E2E Tests
on:
  pull_request:
  push:
    branches:
      - main
      - dev

env:
  DATABASE_URL: 'https://fake.com'
  NEXTAUTH_SECRET: 'fake'
  NEXTAUTH_URL: 'https://fake.com'
  PETFINDER_KEY: 'fake'
  PETFINDER_SECRET: 'fake'
  GOOGLE_ID: 'fake'
  GOOGLE_SECRET: 'fake'
  EMAIL_SERVER_USER: 'fake'
  EMAIL_SERVER_PASSWORD: 'fake'
  EMAIL_SERVER_HOST: 'fake'
  EMAIL_SERVER_PORT: 'fake'
  EMAIL_FROM: 'fake'
  UPLOADTHING_SECRET: 'fake'
  UPLOADTHING_APP_ID: 'fake'

jobs:
  setup:
    name: E2E Tests Setup
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 600
  e2e:
    needs: setup
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
        env:
          PLAYWRIGHT_BASE_URL: ${{ needs.setup.outputs.preview_url }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
