name: Lighthouse Audits

on:
  schedule:
    - cron: '0 0 * * *' # run audits every day at midnight UTC

jobs:
  lighthouse-audits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAGES_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install && npm install -g @lhci/cli@0.11.x

      - name: Run lighthouse audits on landing page for mobile
        run: npm run audit:mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Run lighthouse audits on landing page for desktop
        run: npm run audit:desktop
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
