name: Security Scan

on:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.3.0
        with:
          token: ${{ secrets.GH_PAGES_TOKEN }}
          target: 'https://podopieczni-21142.vercel.app'
