name: Typescript Type Check, Prettier and ESLint CI

on:
  push:
  pull_request:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  PETFINDER_KEY: ${{ secrets.PETFINDER_KEY }}
  PETFINDER_SECRET: ${{ secrets.PETFINDER_SECRET }}
  GOOGLE_ID: ${{ secrets.GOOGLE_ID }}
  GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
  EMAIL_SERVER: ${{ secrets.EMAIL_SERVER }}
  EMAIL_FROM: ${{ secrets.EMAIL_FROM }}

jobs:
  build:
    name: Typescript Type Check, Prettier and ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Typescript typecheck
        run: npm run typecheck

      - name: Format with Prettier
        run: npm run prettier

      - name: Lint with ESLint
        run: npm run lint
