name: Dependency Update Check

on:
  workflow_dispatch:
  # Schedule the job to run on the first day of every month at midnight
  schedule:
    - cron: '0 0 1 * *'

env:
  DATABASE_URL: 'https://fake.com'
  NEXTAUTH_SECRET: 'fake'
  NEXTAUTH_URL: 'https://fake.com'
  PETFINDER_KEY: 'fake'
  PETFINDER_SECRET: 'fake'
  GOOGLE_ID: 'fake'
  GOOGLE_SECRET: 'fake'
  EMAIL_SERVER_USER: 'fake'
  EMAIL_SERVER_PASSWORD: 'fake'
  EMAIL_SERVER_HOST: 'fake'
  EMAIL_SERVER_PORT: 'fake'
  EMAIL_FROM: 'fake'
  UPLOADTHING_SECRET: 'fake'
  UPLOADTHING_APP_ID: 'fake'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Check for updates
        run: npx npm-check-updates --upgrade --jsonUpgraded
        id: check

      - name: Create a pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_PAGES_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          branch: update-dependencies
          body: |
            ```
            ${{ steps.check.outputs.upgraded }}
            ```
          labels: dependencies
          base: dev
